version: "3.5"
services:

  sui:
    container_name: sui
    restart: always
    build:
      context: ./
    environment:
      - VIRTUAL_HOST=test.laserr.net
    networks:
      - nginx-proxy
      - public
    ports:
      - 4000:80
    volumes:
      - ./:/usr/share/nginx/html

networks:
  nginx-proxy:
    external: true
  public:
    external:
      name: public
